baseURL = 'https://abhi84p.github.io/'
languageCode = 'en-us'
title = 'Abhishek Poudel'
theme = 'hugo-bearblog'

[params]
  favicon = "favicon.png"
  description = "Abhishek Poudel's blog."
  footer = "© Abhishek Poudel"
  email = "abhishekpoudel84@gmail.com"

[taxonomies]
  tag = "tags"

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2

[[menu.main]]
  name = "GitHub"
  url = "https://github.com/abhi84P"
  weight = 3

[[menu.main]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/abhishek-poudel-1272a6234/"
  weight = 4
